sudo: required

services:
    - docker

before_install:
    - docker build -t you2better .
    - docker run -d -p 8888:8888 you2better

script:
    - curl http://localhost:8888/?youtubeid=meT2eqgDjiM -o PomplamooseMusic_Beat_it.m4a
